### ISSUE TITLE
Rubgems pubilsh action

### ISSUE THREAD

**Issue by sergio-fry** [HeavyTechRuby/bddsm#3]
After new release tag is added, new gem should be build and published

**Comment by sergio-fry** [comment]
We have an error:

```
bundler: failed to load command: rake (/opt/hostedtoolcache/Ruby/3.3.3/x64/bin/rake)
/opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.4/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.4/lib/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/bin/rake:25:in `<top (required)

```

https://github.com/HeavyTechRuby/bddsm/actions/runs/9747319260/job/26899826861

**Comment by sergio-fry** [comment]
A new error:

```
  
Run bundle exec rake release
  
rake aborted!
Don't know how to build task 'release' (See the list of available tasks with `rake --tasks`)
/home/runner/work/bddsm/bddsm/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.3/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.3/x64/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```

https://github.com/HeavyTechRuby/bddsm/actions/runs/9757234217/job/26929178450

**Comment by sergio-fry** [comment]
An error again


```
rake aborted!
Running `git push origin refs/heads/HEAD` failed with the following output:
error: src refspec refs/heads/HEAD does not match any
error: failed to push some refs to 'https://github.com/HeavyTechRuby/bddsm'
/home/runner/work/bddsm/bddsm/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.3/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.3/x64/bin/bundle:25:in `<main>'
Tasks: TOP => release => release:source_control_push
(See full trace by running task with --trace)

```

https://github.com/HeavyTechRuby/bddsm/actions/runs/9773500375/job/26979793959#step:4:27

**Comment by sergio-fry** [comment]
Fixed here https://github.com/HeavyTechRuby/bddsm/commit/3ca9ffa00caa219ee9308fafc4fab97b6e9f4340
